### ISSUE TITLE
hyperctl doesn't use non-default amazon regions

### ISSUE THREAD

**Issue by molikd** [hyperspike/hyperctl#9]
```
 16:08:09 dmolik@Davids-MacBook-Pro.local {~}$  hyperctl create
time="2021-01-21T16:08:17-05:00" level=error msg="AccessDeniedExceptionAccessDeniedException: You don't have permissions to access this resource.\n\tstatus code: 400, request id: ba8599ec-bdcf-494c-8832-653e13bc9d44"
time="2021-01-21T16:08:17-05:00" level=error msg="AccessDeniedException: User: arn:aws:iam::572725218682:user/dmolik is not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:

us-east-2

:572725218682:table/hyperspike with an explicit deny\n\tstatus code: 400, request id: ON5HVLC8SA77DOJ6AJNMGEMF4VVV4KQNSO5AEMVJF66Q9ASUAAJG"
```

extra lines for emphasis. 

this is actually really important for us because our us-east-2 cluster API is broken.

**Comment by dmolik** [comment]
Have you tried the --region option?On Jan 21, 2021 4:13 PM, David Molik <notifications@github.com> wrote:
 16:08:09 dmolik@Davids-MacBook-Pro.local {~}$  hyperctl create
time="2021-01-21T16:08:17-05:00" level=error msg="AccessDeniedExceptionAccessDeniedException: You don't have permissions to access this resource.\n\tstatus code: 400, request id: ba8599ec-bdcf-494c-8832-653e13bc9d44"
time="2021-01-21T16:08:17-05:00" level=error msg="AccessDeniedException: User: arn:aws:iam::572725218682:user/dmolik is not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:

us-east-2

:572725218682:table/hyperspike with an explicit deny\n\tstatus code: 400, request id: ON5HVLC8SA77DOJ6AJNMGEMF4VVV4KQNSO5AEMVJF66Q9ASUAAJG"

extra lines for emphasis.
this is actually really important for us because our us-east-2 cluster API is broken.

**Comment by molikd** [comment]
--region works!

we should still track down why the environmental variable doesn't work.

**Comment by dmolik** [comment]
the environment variable is working now, this is due to the dynamodb global state table always using us-east-2 for at minimum replication.
